version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    network_mode: bridge  # 🔧 esto permite conexión externa
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://gondola.proxy.rlwy.net:44004/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: zXTDxgHwEPSdorJxPrOjxeXyQIqvhzCD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  frontend:
    build: ./Front
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: libroredsocial
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: