services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: libroredsocial_db
      POSTGRES_USER: libroredsocial_db_user
      POSTGRES_PASSWORD: 2ZC3Dp1ewchytkITaI3e9l9lcRn6ntW5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/libroredsocial_db
      SPRING_DATASOURCE_USERNAME: libroredsocial_db_user
      SPRING_DATASOURCE_PASSWORD: 2ZC3Dp1ewchytkITaI3e9l9lcRn6ntW5
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  frontend:
    build: ./Front
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
